---
abstract: 'Finds broken links (including images) on a website.'
author:
  - 'Paul Waring <paul.waring@manchester.ac.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-BrokenLinks
requires:
  IO::Handle: 0
  Moose: 0
  Text::CSV: 0
  URI: 0
  WWW::Mechanize: 0
  namespace::autoclean: 0
  perl: 5.014
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/pwaring/WWW-BrokenLinks/issues
version: 0.04
